# Generated by Django 3.0.8 on 2020-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200721_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/theblog/images/default_profile_pic.png', null=True, upload_to='images/profile/'),
        ),
    ]
